// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// eloint
List eloint(CharacterVector winner, CharacterVector loser, CharacterVector allids, NumericVector kval, NumericVector startvalues, NumericVector runs);
RcppExport SEXP EloChoice_eloint(SEXP winnerSEXP, SEXP loserSEXP, SEXP allidsSEXP, SEXP kvalSEXP, SEXP startvaluesSEXP, SEXP runsSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< CharacterVector >::type winner(winnerSEXP );
        Rcpp::traits::input_parameter< CharacterVector >::type loser(loserSEXP );
        Rcpp::traits::input_parameter< CharacterVector >::type allids(allidsSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type kval(kvalSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type startvalues(startvaluesSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type runs(runsSEXP );
        List __result = eloint(winner, loser, allids, kval, startvalues, runs);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// elointnorm
List elointnorm(CharacterVector winner, CharacterVector loser, CharacterVector allids, NumericVector kval, NumericVector startvalues, NumericVector runs);
RcppExport SEXP EloChoice_elointnorm(SEXP winnerSEXP, SEXP loserSEXP, SEXP allidsSEXP, SEXP kvalSEXP, SEXP startvaluesSEXP, SEXP runsSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< CharacterVector >::type winner(winnerSEXP );
        Rcpp::traits::input_parameter< CharacterVector >::type loser(loserSEXP );
        Rcpp::traits::input_parameter< CharacterVector >::type allids(allidsSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type kval(kvalSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type startvalues(startvaluesSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type runs(runsSEXP );
        List __result = elointnorm(winner, loser, allids, kval, startvalues, runs);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
